# Generated by Django 4.1.3 on 2022-12-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
