# Generated by Django 4.1.3 on 2022-12-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='users',
            new_name='user',
        ),
    ]
