# Generated by Django 4.1.3 on 2022-12-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0005_ingredients"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ingredients",
        ),
    ]
