# Generated by Django 4.1.3 on 2022-12-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_recipe_category'),
        ('food', '0006_delete_ingredients'),
    ]

    operations = [
    ]
