# Generated by Django 4.1.3 on 2022-12-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_merge_20221206_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.TextField(),
        ),
    ]
