# Generated by Django 4.1.3 on 2022-12-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0008_alter_ingredient_options_alter_recipe_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="inputingerdients",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
